version: "3.8"
services:
  db:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hospital
    ports:
      - "5438:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=host=db user=postgres password=admin dbname=hospital port=5432 sslmode=disable
