// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
  "schemes": {{ marshal .Schemes }},
  "swagger": "2.0",
  "info": {
    "description": "{{escape .Description}}",
    "title": "{{.Title}}",
    "contact": {
      "name": "API Support",
      "url": "http://www.swagger.io/support",
      "email": "support@swagger.io"
    },
    "version": "{{.Version}}"
  },
  "host": "{{.Host}}",
  "basePath": "{{.BasePath}}",
  "paths": {
    "/api/patients": {
      "get": {
        "summary": "Get all patients",
        "description": "Returns a list of all patients.",
        "produces": ["application/json"],
        "responses": {
          "200": {
            "description": "A list of patients",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Patient"
              }
            },
            "examples": {
              "application/json": [
                { "ID": 1, "Name": "Mrs. Sheila Brakus", "Age": 87, "Gender": "Female", "Address": "" },
                { "ID": 2, "Name": "Princess Dana Legros", "Age": 65, "Gender": "Male", "Address": "" },
                { "ID": 3, "Name": "Dr. Janae Mayert", "Age": 31, "Gender": "Male", "Address": "" },
                { "ID": 4, "Name": "Prof. Felicia Sauer", "Age": 68, "Gender": "Male", "Address": "" },
                { "ID": 5, "Name": "Mrs. Nyah Daugherty", "Age": 63, "Gender": "Female", "Address": "" },
                { "ID": 6, "Name": "Princess Hulda Glover", "Age": 36, "Gender": "Female", "Address": "" },
                { "ID": 7, "Name": "Prof. Aglae Beer", "Age": 77, "Gender": "Female", "Address": "" },
                { "ID": 8, "Name": "Lady Kacie Toy", "Age": 69, "Gender": "Male", "Address": "" },
                { "ID": 9, "Name": "Queen Evelyn Rutherford", "Age": 93, "Gender": "Male", "Address": "" },
                { "ID": 10, "Name": "Mrs. Alessandra Moore", "Age": 32, "Gender": "Male", "Address": "" },
                { "ID": 11, "Name": "", "Age": 0, "Gender": "Male", "Address": "123 Main St, City, Country" }
              ]
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Patient": {
      "type": "object",
      "properties": {
        "ID": { "type": "integer", "format": "int32" },
        "Name": { "type": "string" },
        "Age": { "type": "integer", "format": "int32" },
        "Gender": { "type": "string" },
        "Address": { "type": "string" }
      }
    }
  }
}`

func init() {
	swag.Register("swagger", &swag.Spec{
		Version:          "1.0",
		Host:             "localhost:8080",
		BasePath:         "/api",
		Schemes:          []string{},
		Title:            "Hospital API",
		Description:      "This is the API documentation for the Hospital system.",
		InfoInstanceName: "swagger",
		SwaggerTemplate:  docTemplate,
	})
}
