basePath: /api
definitions:
  models.Patient:
    properties:
      Address:
        type: string
      Age:
        type: integer
      Gender:
        type: string
      ID:
        type: integer
      Name:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is the API documentation for the Hospital system.
  title: Hospital API
  version: "1.0"
paths:
  /api/patients:
    get:
      consumes:
      - application/json
      description: Get all patients data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Patient'
            type: array
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get list of patients
      tags:
      - patients
swagger: "2.0"
